# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: Visualarity
fullTitle: Visualarity Comunications Inc.
tagline: Solid Corporate Communication
email: visual@visualarity.com
baseurl: "/visualarity" # the subpath of your site, e.g. /blog
url: "http://nmartinet.github.io" # the base hostname & protocol for your site

companyInfo:
  name: Visualarity Communications Inc.
  address:
    street-address: '625 René-Lévesque West, Suite 920'
    locality: Montréal
    region: Québec
    postal-code: 'H3B 1R2'
    country: 'Canada'
  telephone-no: '514-866-1208'
  fax-no: '514-866-9238'


# Build settings
markdown: kramdown
